### ISSUE TITLE
1.4.3/1.4.4 fails on Centos 5

### ISSUE THREAD

**Issue by krbvroc1** [dimipaun/safekeep#20]
It would appear that git commit 5682e235a17811d4236a58905129e171be77e020 from @livenson added the following:

```
   # XXX a not so elegant branching
   script = cfg['script'].split(':', 1)[1] if mode == 'server' else script
   debug('%s_side_script: script = %s' % (mode, script))
```

Centos 5 systems  use python 2.4 which does not support the ternary operator added in python 2.5 so
backup fails due to syntax error:

```
   File "/usr/bin/safekeep", line 809
     script = cfg['script'].split(':', 1)[1] if mode == 'server' else script
                                              ^
SyntaxError: invalid syntax
```

**Comment by krbvroc1** [comment]
Equivalent python 2.4 compatible code would be:

```
       if mode == 'server':
            script = cfg['script'].split(':', 1)[1] 
        else:
            script = script
```

**Comment by livenson** [comment]
Out of curiosity -- for what kind of a solution it still makes sense to run 12 year old platform?

Not trolling/objecting to backporting, just curios.

**Comment by krbvroc1** [comment]
@livenson Centos 5 is still officially supported by the vendor with security updates until March 31, 2017 and safekeep claims to be compatible with it.

As far as my particular usage, I have some custom modifications / C code for some legacy applications that rely on the Centos 5 versions.  It has been on my todo list for a while to port all that code to a newer version, but it is not trivial due to some API changes and some old web applications relying on older versions of PHP, etc. This is my only server running Centos 5, all other servers in my life runs the latest Centos 7.

EDIT: By the way, I remember upgrading this server from RHEL4! It has actually been running for more than 12 years (3 hardware upgrades though).

**Comment by frankcrawford** [comment]
@krbvroc1 thanks for the report.  Someone else also reported it the other day and I've got them to test a fix, which I'm just about to push to GitHub.  Out of interest the updated line is:

if mode == 'server': script = cfg['script'].split(':', 1)[1]

However, longer term I'll probably fix it a different way, as that line shouldn't be needed at this point in the execution, but I've obviously missed some of the places where it should have been cleaned up.

I'll also push out an update to the EPEL for EL5 to fix this, but won't do anything special about other systems, until the next full release.

**Comment by frankcrawford** [comment]
Okay, the patch has now been pushed to GitHub and an update has been submitted to EPEL.

**Comment by krbvroc1** [comment]
@frankcrawford Thank you - as soon as it hits my server and I test, I'll close this. I appreciate the quick turnaround.

**Comment by krbvroc1** [comment]
@frankcrawford - The fix finally made it to EPEL stable. Tested ok. Thanks.
